name: cd

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    if: >
      github.event.pull_request.merged == true 
    name: Build and Push Docker Image
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push igniz-ai Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:latest
          build-args: |
            BASE_API_URL=${{ secrets.BASE_API_URL }}
            AUTHORIZATION_TOKEN=${{ secrets.AUTHORIZATION_TOKEN }}

  deploy:
    if: >
      github.event.pull_request.merged == true
    name: Deploy using Docker
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} > ~/.ssh/known_hosts

      - name: Deploy Docker Container
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BASE_API_URL: ${{ secrets.BASE_API_URL }}
          AUTHORIZATION_TOKEN: ${{ secrets.AUTHORIZATION_TOKEN }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
          PORT: ${{ secrets.PORT }}
        run: |
          ssh -T ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF

          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

          docker container rm -f igniz-ai || true

          docker system prune -a -f

          docker pull $DOCKER_USERNAME/$REPOSITORY_NAME:latest AUTHORIZATION_TOKEN

          docker run -d --restart unless-stopped -p ${PORT}:80 --name igniz-ai -e BASE_API_URL=$BASE_API_URL -e AUTHORIZATION_TOKEN=$AUTHORIZATION_TOKEN $DOCKER_USERNAME/$REPOSITORY_NAME:latest

          EOF
